spring.application.name=qs
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/test}
spring.data.mongodb.database=${DATABASE:test}
viacep.api.base-url=${VIACEP_API_BASE_URL:https://viacep.com.br/ws}
